sudo: required

env:
  DOCKER_COMPOSE_VERSION: 1.5.2

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  - docker login --username "${DOCKER_USERNAME}" --email "${DOCKER_EMAIL}" --password "${DOCKER_PASSWORD}"
  - cp -r . test/nessus
  - cd test && docker-compose build

script:
  - docker-compose run nessus-test sh -c 'cd /nessus; python -m unittest -v'
