sudo: required

services:
  - docker

before_install:
  - docker login --username "${DOCKER_USERNAME}" --email "${DOCKER_EMAIL}" --password "${DOCKER_PASSWORD}"
  - cd test && docker-compose build

script:
  - docker-compose run python -m unittest -v
